# Generated by Django 4.0.2 on 2022-02-07 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aboutus_options_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('select_mode', models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('InCompleted', 'InCompleted')], max_length=200, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('team1_player_score', models.IntegerField()),
                ('team2_player_score', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_score', to='app.hostmatch')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hostmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team2Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hostmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='HostInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Decline', 'Decline'), ('Attend', 'Attend')], max_length=200, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostmatch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostmatch', to='app.hostmatch')),
                ('user_invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.profile')),
            ],
        ),
    ]
