# Generated by Django 4.0.2 on 2022-02-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hostmatch_teamscore_teamplayers_team2player_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostinvitation',
            unique_together={('hostmatch_id', 'user_invited')},
        ),
    ]
