# Generated by Django 4.0.2 on 2022-02-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hostinvitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostinvitation',
            unique_together=set(),
        ),
    ]
