# Generated by Django 4.0.2 on 2022-02-09 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_rename_team2player_team2players_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=250, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'ios'), ('Android', 'Android')], max_length=250)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 2, 9, 10, 51, 40, 742424, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
