# Generated by Django 4.0.2 on 2022-02-09 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 10, 58, 8, 957783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostmatch',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('incompleted', 'Incompleted')], max_length=200, null=True),
        ),
    ]
