# Generated by Django 4.0.2 on 2022-02-14 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_device_delete_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmatch',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Cancel', 'cancel')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('token_type', models.CharField(choices=[('verification', 'Email Verification'), ('pwd_reset', 'Password Reset')], max_length=20)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expired_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
